apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::329599629534:role/eksctl-expense1-nodegroup-expense-NodeInstanceRole-ofcG1dspKfy8
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - default-trainee
      userarn: arn:aws:iam::329599629534:user/soumya
      username: soumya
kind: ConfigMap
metadata:
  creationTimestamp: "2025-03-16T22:28:52Z"
  name: aws-auth
  namespace: kube-system
  uid: b0f4fd82-e3c8-42c8-be31-ee4753902570
